language: node_js
node_js: '12'
cache:
  directories:
    - node_modules
install:
  - npm install
env: VUE_APP_GITHUB_PAGES=true
before_deploy:
  - npm run build -- --report
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
